# Generated by Django 3.0.7 on 2020-06-30 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlasterboardPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boardm2cost', models.CharField(default='', max_length=100)),
                ('boardsize', models.DecimalField(blank=True, decimal_places=2, default=2.4, max_digits=3, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlasterboardCoverage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boardM2Required', models.CharField(default='', max_length=100)),
                ('boardsize', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculator.PlasterboardPrice')),
            ],
        ),
    ]
